(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var D2=function(a){a.P("cardstatechange",g.mK(a)&&g.nK(a)?1:0)},cra=function(a){if(/-[a-z]/.test("pollChoiceIndex"))return null;
if(g.Ij&&a.dataset){if(g.uc()&&!("pollChoiceIndex"in a.dataset))return null;a=a.dataset.pollChoiceIndex;return void 0===a?null:a}return a.getAttribute("data-"+g.Sc("pollChoiceIndex"))},dra=function(a){return Math.pow(a,3)},era=function(a){return 3*a*a-2*a*a*a},E2=function(a,b){var c=g.io("use_default_events_client")?void 0:g.nq;
(0,g.x)(b,function(d){d={csn:a,ve:g.ur(d),eventType:4};var e={Lk:g.Br(a),Ti:a};"UNDEFINED_CSN"==a?g.Or("visualElementShown",d,e):c?g.Dp("visualElementShown",d,c,e):g.oq("visualElementShown",d,e)})},F2=function(a,b){var c=g.io("use_default_events_client")?void 0:g.nq;
(0,g.x)(b,function(d){var e=void 0;e=void 0===e?!1:e;d={csn:a,ve:g.ur(d),eventType:e?16:8};e={Lk:g.Br(a),Ti:a,PE:e};"UNDEFINED_CSN"==a?g.Or("visualElementHidden",d,e):c?g.Dp("visualElementHidden",d,c,e):g.oq("visualElementHidden",d,e)})},I2=function(a){a=g.Sa(a);
delete G2[a];g.y.isEmpty(G2)&&H2&&H2.stop()},gra=function(){H2||(H2=new g.H(function(){fra()},20));
var a=H2;a.isActive()||a.start()},fra=function(){var a=(0,g.C)();
g.y.forEach(G2,function(b){hra(b,a)});
g.y.isEmpty(G2)||gra()},J2=function(a,b,c,d){g.tn.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.w=a;this.G=b;this.duration=c;this.C=d;this.coords=[];this.progress=this.F=0;this.B=null},hra=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.F=1E3/(b-a.B);a.B=b;ira(a,a.progress);1==a.progress?(a.o=0,I2(a),a.md(),a.lm()):a.Ya()&&a.Pt()},ira=function(a,b){g.Pa(a.C)&&(b=a.C(b));
a.coords=Array(a.w.length);for(var c=0;c<a.w.length;c++)a.coords[c]=(a.G[c]-a.w[c])*b+a.w[c]},jra=function(a,b){g.qe.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.F;this.state=b.o},K2=function(a,b,c,d,e){J2.call(this,b,c,d,e);
this.element=a},L2=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
K2.call(this,a,b,c,d,e)},M2=function(a){g.A.call(this);
this.u=a||window;this.o=[]},kra=function(a,b,c,d){c=(0,g.w)(c,d||a.u);
b=g.lp(b,"change",c,"iv-card-poll-choice-input");a.o.push(b)},N2=function(a){return a.baseUrl||null},O2=function(a,b){return(0,g.ce)((0,g.ic)(a,b,void 0),function(c){return!!c})},lra=function(a,b,c){function d(Ac){var $b=Ac.hovercardButton;
if(!$b)return null;$b=$b.subscribeButtonRenderer;if(!$b)return null;var Gc=f($b.unsubscribedButtonText),Fg=f($b.subscribedButtonText);if($b.subscribed){var Eg=f($b.subscriberCountWithUnsubscribeText);var Tm=f($b.subscriberCountText)}else Eg=f($b.subscriberCountText),Tm=f($b.subscriberCountWithSubscribeText);var Zi=null;return Ac.signinEndpoint&&(Zi=g.y.oi(Ac,"signinEndpoint","webNavigationEndpointData","url"),!Zi)?null:Gc&&(Fg||Zi)?{subscribed:$b.subscribed,subscribeText:Gc,subscribeCount:Eg,unsubscribeText:Fg,
unsubscribeCount:Tm,enabled:$b.enabled,signinUrl:Zi,classic:Ac.useClassicSubscribeButton}:null}
function e(Ac){if(Ac){var $b=[],Gc=Ac.videoId;Gc&&$b.push("v="+Gc);(Gc=Ac.playlistId)&&$b.push("list="+Gc);(Ac=Ac.startTimeSeconds)&&$b.push("t="+Ac);return"/watch?"+$b.join("&")}}
function f(Ac){if(!Ac)return null;var $b=Ac.simpleText;return $b?$b:Ac.runs?(0,g.ic)(Ac.runs,function(Gc){return Gc.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var k=b.style,l=b.endpoint||{},m=null,n=null,p=null,t=null,u=null,z=null,D=!1,E=null,F=null,G=null,K=null,ma=null;if("VIDEO"==k)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,p=a,t=f(b.videoDuration);else if("PLAYLIST"==k)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,p=a,u=f(b.playlistLength);else if("CHANNEL"==k){if(D=g.y.oi(l,"browseEndpoint","browseId"))z=D,m="/channel/"+z;n=!1;p="new";(D=!!b.isSubscribe)?E=d(b):F=f(b.subscribersText)}else"WEBSITE"==
k?((G=g.y.oi(l,"urlEndpoint","url"))&&(m=G),n=!0,p="new",G=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"==k&&(b.productPrice&&(K=f(b.productPrice)),b.additionalFeesText&&(ma=f(b.additionalFeesText)),(n=g.y.oi(l,"urlEndpoint","url"))&&(m=n),n=!0,p="new");a=g.y.oi(b,"title","accessibility","accessibilityData","label");var ta=b.endpoint?b.endpoint.clickTrackingParams:null,rc="";if(b.metadata){var Wd=f(b.metadata);Wd&&(rc=Wd)}return{id:"element-"+c,type:k,title:f(b.title),metadata:rc,callToAction:f(b.callToAction),
Hw:b.image,iconUrl:G,left:parseFloat(b.left),width:parseFloat(b.width),top:parseFloat(b.top),aspectRatio:parseFloat(b.aspectRatio),startMs:parseInt(b.startMs,10),endMs:parseInt(b.endMs,10),videoDuration:t,playlistLength:u,channelId:z,subscribeButton:E,subscribersText:F,isSubscribe:D,targetUrl:m,oG:n,Ob:{itct:ta},WO:p,Dk:a?a:null,tG:b.isPlaceholder,impressionUrls:O2(b.impressionUrls||[],N2),gG:O2(b.hovercardShowUrls||[],N2),clickUrls:O2(l.loggingUrls||[],N2),visualElement:g.sr(b.trackingParams),productPrice:K,
additionalFeesText:ma}},P2=function(a,b){var c={};
c.startMs=parseInt(a.startMs,10);c.impressionUrls=O2(a.impressionUrls||[],N2);a.trackingParams&&(c.visualElement=g.sr(a.trackingParams));c.elements=O2(a.elements||[],function(d,e){return lra(b,d,e)});
return c},Q2=function(a){g.KK.call(this,a);
this.A=this.u=null;this.o={};this.F={};this.C=this.w=null;this.H=[];a=a.N();this.J=g.fy(a)||g.hy(a);this.M=!0;this.G=0;this.B=new g.O(this);g.B(this,this.B);this.B.L(this.player,g.KC("creatorendscreen"),this.hH);this.B.L(this.player,"crx_creatorendscreen",this.iH);this.B.L(this.player,"resize",this.Qy);this.B.L(window,"focus",this.TN);this.load();var b=g.Xd("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.ne(this,function(){g.be(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},mra=function(a){return a.player.getVideoData().Dc?"current":a.J?"new":"current"},R2=function(a){return"creator-endscreen-editor"===a.player.N().playerStyle},S2=function(a,b,c){c=void 0===c?!0:c;
g.MP(a.player.app,"creatorendscreen",void 0);a.w&&(a.w.dispose(),a.w=null,a.C.dispose(),a.C=null);for(var d in a.o)a.o[d].dispose();a.o={};a.F={};0<a.H.length&&(a.H.forEach(function(l){l.dispose()}),a.H.length=0);
a.G=0;if((a.u=b)&&b.elements){c&&nra(a);c=[];d=new g.HC(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.N().o||(a.w=new g.Q({D:"div",I:"ytp-ce-shadow"}),g.xK(a.player,a.w.element,4),a.C=new g.fL(a.w,200));for(d=0;d<b.elements.length;++d){var e=b.elements[d],f=ora(a,e);a.o[e.id]=f;a.F[e.id]=e;g.xK(a.player,f.element,4);var k=new g.HC(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(k);pra(a,f,e)}g.tK(a.player,c);
a.Qy()}},nra=function(a){var b=g.yr(),c=g.Ar();
c&&b&&a.u.visualElement&&g.Ur(c,b,a.u.visualElement)},ora=function(a,b){var c=null;
switch(b.type){case "VIDEO":c={D:"div",Y:["ytp-ce-element","ytp-ce-video"],O:{tabindex:"0","aria-label":b.Dk||"","aria-hidden":"true"},K:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-covering-image",O:T2(b)},{D:"div",I:"ytp-ce-covering-shadow-top"},{D:"a",I:"ytp-ce-covering-overlay",O:{href:U2(a,b.targetUrl),tabindex:"-1"},K:[{D:"div",Y:["ytp-ce-video-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],O:{dir:g.Nm(b.title||"")},W:b.title},{D:"div",I:"ytp-ce-video-duration",W:b.videoDuration}]}]};
c=new g.Q(c);break;case "PLAYLIST":c={D:"div",Y:["ytp-ce-element","ytp-ce-playlist"],O:{tabindex:"0","aria-label":b.Dk||"","aria-hidden":"true"},K:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-covering-image",O:T2(b)},{D:"div",I:"ytp-ce-covering-shadow-top"},{D:"a",I:"ytp-ce-covering-overlay",O:{href:U2(a,b.targetUrl),tabindex:"-1"},K:[{D:"div",Y:["ytp-ce-playlist-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],O:{dir:g.Nm(b.title||"")},W:b.title},{D:"div",I:"ytp-ce-playlist-count",K:[{D:"div",
I:"ytp-ce-playlist-icon"},{D:"div",I:"ytp-ce-playlist-count-text",W:b.playlistLength}]}]}]};c=new g.Q(c);break;case "CHANNEL":c={D:"div",Y:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],O:{tabindex:"0","aria-label":b.Dk||"","aria-hidden":"true"},K:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-expanding-overlay",K:[{D:"div",I:"ytp-ce-expanding-overlay-hider"},{D:"div",I:"ytp-ce-expanding-overlay-background"},{D:"div",I:"ytp-ce-expanding-overlay-content",
K:[{D:"div",I:"ytp-ce-expanding-overlay-body",K:[{D:"div",I:"ytp-ce-expanding-overlay-body-padding",K:[{D:"a",Y:["ytp-ce-channel-title","ytp-ce-link"],O:{href:U2(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Nm(b.title||"")},W:b.title},b.subscribeButton?{D:"div",I:"ytp-ce-subscribe-container",K:[{D:"div",I:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{D:"div",I:"ytp-ce-channel-subscribers-text",W:b.subscribersText}:"",b.metadata?{D:"div",Y:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],
W:b.metadata}:""]}]}]}]},{D:"div",I:"ytp-ce-expanding-image",O:T2(b)}]};c=new g.Q(c);var d=g.Id(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.I(d,"ytp-ce-subscribe-button");if(a.player.N().o){var e=null;var f=b.Ob.itct}else e="endscreen",f=null;e=new g.aP(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,b.subscribeButton.enabled,b.subscribeButton.classic,b.channelId,
!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.H.push(e)}break;case "WEBSITE":c={D:"div",Y:["ytp-ce-element","ytp-ce-website"],O:{tabindex:"0","aria-label":b.Dk||"","aria-hidden":"true"},K:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-expanding-overlay",K:[{D:"div",I:"ytp-ce-expanding-overlay-hider"},{D:"div",I:"ytp-ce-expanding-overlay-background"},{D:"div",I:"ytp-ce-expanding-overlay-content",K:[{D:"div",I:"ytp-ce-expanding-overlay-body",
K:[{D:"div",I:"ytp-ce-expanding-overlay-body-padding",K:[{D:"div",I:"ytp-ce-website-title",O:{dir:g.Nm(b.title||"")},W:b.title},{D:"div",I:"ytp-ce-website-metadata",W:b.metadata},{D:"a",Y:["ytp-ce-website-goto","ytp-ce-link"],O:{href:U2(a,b.targetUrl),target:"_blank",tabindex:"-1"},W:b.callToAction}]}]}]}]},{D:"div",I:"ytp-ce-expanding-image",O:T2(b)},{D:"div",I:"ytp-ce-expanding-icon",O:qra(b.iconUrl)}]};c=new g.Q(c);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={D:"div",I:"ytp-ce-merchandise-price-container",
K:[{D:"div",I:"ytp-ce-merchandise-price",W:b.productPrice}]},b.additionalFeesText&&c.K.push({D:"div",I:"ytp-ce-merchandise-additional-fees",W:b.additionalFeesText})),c={D:"div",Y:["ytp-ce-element","ytp-ce-merchandise"],O:{tabindex:"0","aria-label":b.Dk||"","aria-hidden":"true"},K:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-expanding-overlay",K:[{D:"div",I:"ytp-ce-expanding-overlay-hider"},{D:"div",I:"ytp-ce-expanding-overlay-background"},{D:"div",I:"ytp-ce-expanding-overlay-content",K:[{D:"div",
I:"ytp-ce-expanding-overlay-body",K:[{D:"div",I:"ytp-ce-expanding-overlay-body-padding",K:[{D:"div",I:"ytp-ce-merchandise-title",O:{dir:g.Nm(b.title||"")},W:b.title},c,{D:"div",I:"ytp-ce-merchandise-metadata",W:b.metadata},{D:"a",Y:["ytp-ce-merchandise-goto","ytp-ce-link"],O:{href:U2(a,b.targetUrl),target:"_blank",tabindex:"-1"},W:b.callToAction}]}]}]}]},{D:"div",I:"ytp-ce-expanding-image",O:T2(b)},{D:"div",I:"ytp-ce-merchandise-invideo-cta-container",K:[{D:"div",I:"ytp-ce-merchandise-invideo-cta",
W:b.callToAction}]}]},c=new g.Q(c)}b.tG&&g.I(c.element,"ytp-ce-placeholder");return c},T2=function(a){if(a.Hw)var b=a.Hw.thumbnails;
return qra(b?b[b.length-1].url:null)},qra=function(a){return a?{style:"background-image: url("+a+")"}:{}},pra=function(a,b,c){function d(){k(1)}
function e(){k(-1)}
b.ia("mouseenter",(0,g.w)(a.Ss,a,b,c));b.ia("mouseleave",(0,g.w)(a.Tt,a,b,c));a.player.N().o||b.ia("click",(0,g.w)(function(l){g.I(l.element,"ytp-ce-element-hover")},a,b));
b.ia("click",(0,g.w)(a.xA,a,c));b.ia("keypress",(0,g.w)(a.xA,a,c));b.ia("focus",(0,g.w)(function(l,m){this.Ss(l,m)},a,b,c));
b.ia("blur",(0,g.w)(function(l,m){this.Tt(l,m)},a,b,c));
b.ia("touchstart",(0,g.w)(a.Ss,a,b,c));var f=g.Kd("ytp-ce-expanding-overlay-hider",b.element);f&&b.L(f,"touchstart",function(l){l=l||window.event;l.cancelBubble=!0;l.stopPropagation&&l.stopPropagation();g.rn(b.element,"ytp-ce-element-hover");g.rn(b.element,"ytp-ce-force-expand")});
b.ia("keydown",(0,g.w)(function(l,m){this.M=9==m.keyCode&&!m.shiftKey},a,b));
var k=(0,g.w)(function(l,m,n){this.G+=n;0<this.G?(g.I(l.element,"ytp-ce-force-expand"),V2(this,m.id,!0)):(g.rn(l.element,"ytp-ce-force-expand"),g.rn(l.element,"ytp-ce-element-hover"),V2(this,m.id,!1))},a,b,c);
c=(0,g.w)(function(l,m){m&&(l.ia("blur",g.Ta(function(){"none"!=m.style.display&&a.M&&m.focus()})),l.L(m,"focus",d),l.L(m,"blur",e))},a,b);
c(g.Kd("ytp-sb-subscribe",b.element));c(g.Kd("ytp-sb-unsubscribe",b.element));b.ia("focus",d);b.ia("blur",e)},U2=function(a,b){var c=a.player.N();
if(b){if(b.startsWith("//"))return c.protocol+":"+b;if(b.startsWith("/"))return g.Iy(c)+b}else return"";return b},V2=function(a,b,c){a.w&&(c?a.C.show():a.C.hide());
for(var d in a.o)d!=b&&g.J(a.o[d].element,"ytp-ce-element-shadow-show",c)},W2=function(a,b,c){function d(){f||(e++,e==b.length&&(k.stop(),c&&c()))}
if(!b||0==b.length||R2(a))c&&c();else{b=rra(a,b);var e=0,f=!1,k=new g.H(function(){f=!0;c&&c()},1E3,a);
k.start();for(a=0;a<b.length;a++)g.Aq(b[a],d)}},X2=function(a,b,c){W2(a,b.clickUrls,c);
(a=g.Ar())&&b.oG&&g.Rr(a,b.visualElement)},rra=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(sra(b[e],c));return d},sra=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},tra=function(a){return g.Na(a)&&a.length?a[0]:a},Y2=function(a){return"string"===typeof a?a:""},Z2=function(a,b,c){for(var d in b)if(b[d]==a)return a;
return c},vra=function(a){var b=ura;
if(null==a)return null;if(g.Oa(a)){var c=[];(0,g.x)(a,function(d){(d=b(d))&&c.push(d)});
return c}return(a=b(a))?[a]:[]},wra=function(a){this.externalId=a},xra=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.o=d},$2=function(a){if(!a)return null;
var b=g.cc(Y2(a.value));b=g.ac(b);if(!b)return null;var c=Z2(a.target,yra,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new xra(b,c,"true"==d||"false"==d?"true"==d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},a3=function(a){return a.value?a.value:null},zra=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},ura=function(a){if(!a)return null;
var b=Z2(a.type,Ara),c=Z2(a.trigger,Bra),d=tra(a.url);d=$2(d?d:null);a=tra(a.subscribeData);var e=a?a:null;e?(a=Y2(e.external_user_id),e=Y2(e.subscription_token),a=a&&e?new wra(a):null):a=null;return b?new zra(b,c,d,a):null},b3=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.o=d||[];this.data=e},Cra=function(a,b){return g.$a(a.o,b,void 0)},Dra=function(a,b){return a.id.replace(/[^a-z0-9-]/gi,"-")+"-"+b.toString()},Era=function(a,b){this.merchant=a;
this.price=b},Fra=function(a){this.o=a},Gra=function(a,b,c){b&&(c?c3(a,(0,g.ic)(b,g.Ta(function(d,e){return g.Lm(e,d)},c))):c3(a,b))},c3=function(a,b,c,d){var e=1,f=-1;
if(c){var k=!1;var l=function(){e--;e||k||(clearTimeout(f),k=!0,c())};
f=setTimeout(function(){k=!0;c()},1E3)}(0,g.x)(b||[],function(m){e++;
g.Aq(m,l)});
d&&(e++,0!=d&&a.o.sendVideoStatsEngageEvent(d,l))},Hra=function(a,b,c,d,e,f,k){this.o=a;
this.w=b;this.A=c;this.videoData=d;this.logger=e;this.U=f;this.u=k},d3=function(a,b){this.o=a;
this.w=b},Kra=function(a,b){var c=[];
(0,g.x)(b.choices,function(k){c.push(Ira(b,k))},a);
var d={D:"ul",O:{role:"radiogroup"},K:c},e={};b.Xi&&(e["aria-label"]=g.LL("$POLL_TITLE - Sign in to vote.",{POLL_TITLE:b.title}));var f=["iv-card","iv-card-poll"];d=[{D:"div",I:"iv-card-content",K:[e3("h2",e,b.title),{D:"form",K:[{D:"fieldset",K:[d]}]}]}];b.Xi&&(f.push("iv-card-unavailable"),d.push({D:"div",Y:["iv-card-sign-in"],K:[{D:"h2",W:"Want to vote?"},{D:"a",Y:["iv-card-sign-in-button","iv-button"],O:{href:a3(b.Xi)},K:[{D:"span",Y:["iv-button-content"],W:"Sign in"}]}]}));f=new g.Q({D:"div",
Y:f,K:d});d=f.element;Jra(b,d);kra(a.o.o,d,g.Ta(a.A,b),a);(0,g.x)(g.Jd("iv-card-poll-choice-input",d),function(k){this.o.o.ia(k,"focus",g.Ta(this.u,!0));this.o.o.ia(k,"blur",g.Ta(this.u,!1))},a);
b.Xi&&(d=g.Kd("iv-card-sign-in-button",d),a.w(d,b.Xi,b.id,b.Ob,b.Nc.click,5));return f},Lra=function(a,b,c){var d=["yt-badge",
"standalone-ypc-badge-renderer-icon",b.pP?"standalone-ypc-badge-renderer-icon-purchased":"standalone-ypc-badge-renderer-icon-available"],e={};d=b.sG&&b.cw?{D:"span",Y:d,O:e,W:b.cw}:"";c={D:"div",Y:["iv-card",c],K:[{D:"a",I:"iv-click-target",O:{href:a3(b.url)},K:[f3(b.cj,d?{D:"div",I:"iv-card-image-text",K:[d,b.priceText]}:""),{D:"div",I:"iv-card-content",K:[{D:"h2",I:"iv-card-primary-link",W:b.title},g3(a,b)]}]}]};c=new g.Q(c);h3(a,g.Jd("iv-click-target",c.element),b,b.url);return c},i3=function(a){return a.customMessage?
e3("div","iv-card-message",a.customMessage):""},f3=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{D:"div",I:"iv-card-image",O:{style:c},K:d}},g3=function(a,b){if(!b.metaInfo||0==b.metaInfo.length)return"";
var c=[];(0,g.x)(b.metaInfo,function(d){c.push(e3("li","",d))},a);
return{D:"ul",I:"iv-card-meta-info",K:c}},Ira=function(a,b){return{D:"li",
I:Dra(a,b.index),K:[{D:"label",K:[{D:"input",I:"iv-card-poll-choice-input",O:{type:"checkbox",role:"radio",name:a.id.replace(/[^a-z0-9-]/gi,"-")+b.index.toString(),value:b.index.toString(),"data-poll-choice-index":b.index.toString()}},{D:"span",I:"iv-card-poll-choice-text",K:[{D:"span",I:"iv-card-poll-choice-percent"},e3("span",void 0,b.desc)]}]},{D:"div",I:"iv-card-poll-result",K:[{D:"div",I:"iv-card-poll-result-bar"}]}]}},e3=function(a,b,c){b?"string"===typeof b?b={"class":b}:g.Na(b)&&(b={"class":b.join(" ")}):
b={};
b.dir=g.Nm(c);return{D:a,O:b,W:c}},Mra=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.yn&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.yn+");");c.dir=g.Nm(a.customMessage);var d=[{D:"span",W:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({D:"span",I:"iv-card-link-icon"}));return{D:"div",Y:b,O:c,K:d}},Jra=function(a,b){var c=0;
(0,g.x)(a.choices,function(m){c+=m.count});
c=c||1;for(var d=0;d<a.choices.length;d++){var e=a.choices[d],f=g.Kd(Dra(a,e.index),b);e=e.count/c;null==a.He&&(e=0);g.J(f.getElementsByTagName("label")[0],"iv-card-poll-choice-checked",a.He==d);f.getElementsByTagName("input")[0].checked=a.He==d;var k=Math.floor(100*e).toFixed(0),l=g.Kd("iv-card-poll-choice-percent",f);g.fe(l,g.LL("$PERCENT%",{PERCENT:k}));f=g.Kd("iv-card-poll-result-bar",f);g.ch(f,"transform","scaleX("+e.toFixed(2)+")")}g.J(b,"iv-card-poll-voted",null!=a.He);g.J(b,"iv-card-poll-expanded",
null!=a.He&&1<a.choices.length)},h3=function(a,b,c,d){d&&(0,g.x)(b,function(e){this.w(e,d,c.id,c.Ob,c.Nc.click,5)},a)},Nra=function(a){var b;
(b=a)&&!(b=1<a.length?"/"==a.charAt(0)&&"/"!=a.charAt(1):"/"==a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"==b[0]&&"youtube"==b[1]||"be"==b[0]&&"youtu"==b[1]);return b?-1==a.indexOf("/redirect?"):!1},Ora=function(a,b){return b?b:Nra(a)?"current":"new"},j3=function(a,b){g.A.call(this);
var c=this;this.o=a;this.context=b;this.Vu=!1;this.na=new Map;this.ra=new Map;this.context.U.addEventListener(g.KC("annotations_module"),function(d){(d=c.na.get(d))&&d.apply(c)});
this.context.U.addEventListener("crx_annotations_module",function(d){(d=c.ra.get(d))&&d.apply(c)})},Pra=function(a,b,c,d,e){var f=a3(b);
if(f){var k=Ora(f,b.target),l=(0,g.w)(function(){b.o&&this.context.U.pauseVideo();var m=this.context.videoData.Dc||!1,n=g.Kp(f||"");m&&n&&(n.v||n.list)?g.FS(this.context.U.app,n.v,c,n.list,!1,void 0):g.PL(f||"","current"==k?"_top":void 0,c)},a);
"new"==k&&(l(),l=null);c3(a.context.logger,d,l,e);Nra(f)||(a=g.Ar(),d=c.itct,a&&d&&g.Rr(a,g.sr(d)))}},Qra=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},k3=function(a,b,c){return{Rx:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
qC:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
fq:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl})}},n3=function(a,b,c){j3.call(this,b,c);
var d=this;this.w=a;this.da=this.Ha=this.C=this.Ga=!1;this.ea=null;this.aa=new g.H(g.Ka,c.A.Na?4E3:3E3);g.B(this,this.aa);this.ya=new g.H(g.Ka);g.B(this,this.ya);this.H=new d3(c,(0,g.w)(this.kk,this),(0,g.w)(this.Ho,this));this.T=new g.Q({D:"div",I:"iv-drawer",O:{id:"iv-drawer"},K:[{D:"div",I:"iv-drawer-header",O:{"aria-role":"heading"},K:[{D:"span",I:"iv-drawer-header-text"},{D:"button",Y:["iv-drawer-close-button","ytp-button"],O:{"aria-label":"Hide cards",tabindex:"0"}}]},{D:"div",I:"iv-drawer-content"}]});
g.B(this,this.T);this.F=this.T.element;this.sa=new g.fL(this.T,330);g.B(this,this.sa);this.Ba=g.Kd("iv-drawer-header-text",this.F);this.B=g.Kd("iv-drawer-content",this.F);this.A=[];this.Aa=this.R=this.G=this.ha=this.u=null;this.Z=[];this.addCueRange(0,1E3*c.videoData.lengthSeconds,"",function(){d.Ha&&l3(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Ha=d.C)&&m3(d)});
this.V=this.J=this.ca=null;this.M=0},Rra=function(a,b){b.data.autoOpenMs&&a.addCueRange(b.data.autoOpenMs,0x8000000000000,"",function(){l3(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.data.autoCloseMs&&a.addCueRange(b.data.autoCloseMs,0x8000000000000,"",function(){m3(a)});
var c=b.data.headerText;g.fe(a.Ba,c);a.R&&a.R.setAttribute("title",c);a.ca=g.sr(b.data.trackingParams);a.V=g.sr(b.data.closeTrackingParams);a.J=g.sr(b.data.iconTrackingParams)},Sra=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.M;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.M,type:"simple",teaserText:g.U(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Ob:o3(a,c,b,d),sponsored:!1,Nc:k3(d,e,d.command),je:d.trackingParams?g.sr(d.trackingParams):null,ce:e.trackingParams?
g.sr(e.trackingParams):null,Dd:f&&f.trackingParams?g.sr(f.trackingParams):null,imageUrl:p3(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.U(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,yn:null,title:d.title?g.U(d.title):"",customMessage:d.callToAction?g.U(d.callToAction):"",url:d.command.urlEndpoint.url?$2({pause_on_navigation:!a.context.videoData.ua,target:"new",value:d.command.urlEndpoint.url}):null};q3(a,c)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.M,type:"collaborator",teaserText:g.U(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Ob:o3(a,c,b,d),sponsored:!1,Nc:k3(d,e,d.endpoint),je:d.trackingParams?g.sr(d.trackingParams):null,ce:e.trackingParams?g.sr(e.trackingParams):null,Dd:f&&f.trackingParams?
g.sr(f.trackingParams):null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.U(d.customText):null,vB:p3(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.U(d.channelName):"",metaInfo:[d.subscriberCountText?g.U(d.subscriberCountText):""],url:$2({pause_on_navigation:!a.context.videoData.ua,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};q3(a,c)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.M,type:"playlist",teaserText:g.U(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Ob:o3(a,c,b,d),sponsored:!1,Nc:k3(d,e,d.action),je:d.trackingParams?g.sr(d.trackingParams):null,ce:e.trackingParams?g.sr(e.trackingParams):null,Dd:f&&f.trackingParams?g.sr(f.trackingParams):
null,cj:p3(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.U(d.customMessage):null,playlistVideoCount:g.U(d.playlistVideoCount),title:d.playlistTitle?g.U(d.playlistTitle):"",metaInfo:[d.channelName?g.U(d.channelName):"",d.videoCountText?g.U(d.videoCountText):""],url:$2({pause_on_navigation:!a.context.videoData.ua,target:"new",value:Qra(d.action)})};q3(a,c)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;
e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.M,type:"video",teaserText:g.U(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Ob:o3(a,c,b,d),sponsored:!1,Nc:k3(d,e,d.action),je:d.trackingParams?g.sr(d.trackingParams):null,ce:e.trackingParams?g.sr(e.trackingParams):null,Dd:f&&f.trackingParams?g.sr(f.trackingParams):null,cj:p3(d.videoThumbnail.thumbnails,
258).url,videoDuration:d.lengthString?g.U(d.lengthString):null,customMessage:d.customMessage?g.U(d.customMessage):null,title:d.videoTitle?g.U(d.videoTitle):"",metaInfo:[d.channelName?g.U(d.channelName):"",d.viewCountText?g.U(d.viewCountText):""],isLiveNow:!!d.badge,url:$2({pause_on_navigation:!a.context.videoData.ua,target:"new",value:Qra(d.action)})};q3(a,c)}a.M++},p3=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height==b||290==a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},o3=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId,itct:d.trackingParams}},Ura=function(a,b){var c=Tra(a,b);
c&&(c==a.u&&(a.u=null),a.w.removeCueRange(c.card.id),g.be(c.Yq),g.gb(a.A,c),a.Bn(),r3(a))},l3=function(a,b,c){if(!a.C){a.sa.show();
a.ha=new g.H(function(){g.I(g.cK(a.context.U),"ytp-iv-drawer-open")},0);
a.ha.start();a.ea=g.cp(a.B,"mousewheel",(0,g.w)(a.vH,a));a.C=!0;var d=g.Ar();d&&a.ca&&a.V&&E2(d,[a.ca,a.V]);var e=g.y.create("TRIGGER_TYPE",b);(0,g.x)(a.A,function(f){f.vy||(f.vy=!0,Gra(a.context.logger,f.card.Nc.Rx,e));d&&E2(d,[f.card.je])});
D2(a.w);c&&(a.G=new g.H(function(){a.xa=a.R;a.Aa.focus()},330),a.G.start())}},m3=function(a){a.C&&(a.sa.hide(),g.dp(a.ea),a.ea=null,g.rn(g.cK(a.context.U),"ytp-iv-drawer-open"),a.C=!1,D2(a.w),a.G&&a.G.stop(),a.G=new g.H(function(){a.xa&&(a.xa.focus(),a.xa=null)},330),a.G.start())},Vra=function(a){var b=g.Kd("iv-drawer-close-button",a.F);
a.context.o.ia(b,"click",a.vE,a);a.context.o.ia(a.B,"touchend",function(){a.aa.start()});
a.context.o.ia(a.B,"scroll",a.LE,a);a.context.u.subscribe("onHideControls",function(){a.da=!0});
a.context.u.subscribe("onShowControls",function(){a.da=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.da=g.pn(g.cK(a.w),"ytp-autohide")});
a.Z.push(g.zo("iv-button-shown",a.AG,a));a.Z.push(g.zo("iv-button-hidden",a.zG,a));a.Z.push(g.zo("iv-teaser-shown",a.DG,a));a.Z.push(g.zo("iv-teaser-hidden",a.CG,a));a.Z.push(g.zo("iv-teaser-clicked",a.BG,a))},q3=function(a,b){a.Ga||(g.qn(a.o,["html5-stop-propagation",
"iv-drawer-manager"]),g.xK(a.w,a.F,5),Vra(a),a.R=g.Kd("ytp-cards-button",g.cK(a.w)),a.Aa=g.Kd("iv-drawer-close-button",a.F),a.Ga=!0);Ura(a,b.id);var c=Wra(a,b);if(c){var d={card:b,Yq:c.element,vy:!1},e=Xra(a,d);g.ob(a.A,e,0,d);c.ba(a.B,e);a.Bn();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,g.Ta(a.GO,d)):(c=1E3*a.context.U.getCurrentTime(),5E3>c&&c>b.startMs&&a.aC(d),a.addCueRange(b.startMs,b.startMs+1,b.id,g.Ta(a.aC,d)),r3(a))}},Wra=function(a,b){switch(b.type){case "simple":var c=a.H;
var d=b.displayDomain?{D:"div",I:"iv-card-image-text",W:b.displayDomain}:"";var e=Mra(b);d={D:"div",Y:["iv-card"],K:[{D:"a",I:"iv-click-target",O:{href:a3(b.url)},K:[f3(b.imageUrl,d),{D:"div",I:"iv-card-content",K:[e3("h2",void 0,b.title),e]}]}]};d=new g.Q(d);h3(c,g.Jd("iv-click-target",d.element),b,b.url);return d;case "collaborator":return c=a.H,d={D:"div",Y:["iv-card","iv-card-channel"],K:[{D:"a",Y:["iv-click-target"],O:{href:a3(b.url),"data-ytid":b.channelId},K:[f3(b.vB),{D:"div",I:"iv-card-content",
K:[i3(b),{D:"h2",I:"iv-card-primary-link",W:b.title},g3(c,b)]}]}]},d=new g.Q(d),h3(c,g.Jd("iv-click-target",d.element),b,b.url),d;case "episode":return Lra(a.H,b,"iv-card-episode");case "movie":return Lra(a.H,b,"iv-card-movie");case "playlist":return c=a.H,d={D:"div",Y:["iv-card","iv-card-playlist"],K:[{D:"a",I:"iv-click-target",O:{href:a3(b.url)},K:[f3(b.cj,{D:"div",I:"iv-card-image-overlay",K:[{D:"span",I:"iv-card-playlist-video-count",W:b.playlistVideoCount}]}),{D:"div",I:"iv-card-content",K:[i3(b),
e3("h2","iv-card-primary-link",b.title),g3(c,b)]}]}]},d=new g.Q(d),h3(c,g.Jd("iv-click-target",d.element),b,b.url),d;case "poll":return Kra(a.H,b);case "productListing":c=a.H;var f=!g.db(b.offers);d=["iv-card"];e="";var k=Mra(b);f&&(d.push("iv-card-product-listing"),e="iv-card-primary-link",f=b.offers[0],k=[],f.price&&k.push({D:"div",I:"iv-card-offer-price",W:f.price}),f.merchant&&k.push({D:"div",I:"iv-card-offer-merchant",W:f.merchant}),k={D:"div",K:k});d={D:"div",Y:d,O:{tabindex:"0"},K:[{D:"a",
Y:["iv-card-image","iv-click-target"],O:{style:"background-image: url("+b.imageUrl+");",href:a3(b.url),"aria-hidden":"true",tabindex:"-1"}},{D:"div",I:"iv-card-content",K:[b.sponsored?{D:"div",I:"iv-card-sponsored",K:["Sponsored",{D:"div",I:"iv-ad-info-container",K:[{D:"div",I:"iv-ad-info",W:"{{adInfo}}"},{D:"div",I:"iv-ad-info-icon-container",K:[{D:"div",I:"iv-ad-info-icon"},{D:"div",I:"iv-ad-info-callout"}]}]}]}:"",{D:"a",I:"iv-click-target",O:{href:a3(b.url)},K:[e3("h2",e,b.title),k]}]}]};d=new g.Q(d);
e=g.Xd("span");g.fe(e,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");d.kb(e,"adInfo");h3(c,g.Jd("iv-click-target",d.element),b,b.url);return d;case "video":return c=a.H,d=b.isLiveNow?{D:"span",Y:["yt-badge","yt-badge-live"],W:"LIVE NOW"}:"",d={D:"div",Y:["iv-card","iv-card-video"],K:[{D:"a",I:"iv-click-target",O:{href:a3(b.url)},K:[f3(b.cj,b.videoDuration?{D:"span",I:"iv-card-video-duration",W:b.videoDuration}:""),{D:"div",I:"iv-card-content",
K:[i3(b),e3("h2","iv-card-primary-link",b.title),g3(c,b),d]}]}]},d=new g.Q(d),h3(c,g.Jd("iv-click-target",d.element),b,b.url),d}return null},Xra=function(a,b){if(0==a.A.length)return 0;
var c=g.ab(a.A,function(d){return b.card.startMs>d.card.startMs||b.card.startMs==d.card.startMs&&b.card.timestamp>=d.card.timestamp?!0:!1});
return-1==c?0:c+1},Yra=function(a){return a.u?"productListing"==a.u.card.type:(0,g.bi)(a.A,function(b){return"productListing"==b.card.type})},r3=function(a){g.J(g.cK(a.w),"ytp-cards-shopping-active",Yra(a))},Zra=function(a,b){if(a.T.Fa()){var c=new J2([0,
a.B.scrollTop],[0,b.Yq.offsetTop],600,era);a.context.w.ia(c,"animate",function(d){a.B.scrollTop=d.y});
a.context.w.ia(c,"finish",function(d){a.B.scrollTop=d.y});
c.play()}else g.Ws(a.T,!0),a.B.scrollTop=b.Yq.offsetTop,g.Ws(a.T,!1)},s3=function(a){return a.u&&a.u.card?a.u.card:a.A[0]&&a.A[0].card?a.A[0].card:null},Tra=function(a,b){return g.$a(a.A,function(c){return c.card.id==b})},t3=function(a,b,c){j3.call(this,a,b);
this.annotation=c;this.isActive=!1},$ra=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(a.annotation.data.start_ms,a.annotation.data.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},u3=function(a,b,c){t3.call(this,a,b,c);
this.w=null;this.G=!1;this.A=null;this.B=!1;this.u=this.F=this.C=null},v3=function(a,b,c){t3.call(this,a,b,c);
this.J=this.C=this.M=!1;this.G=5E3;this.B=null;this.H=g.Vd("DIV","iv-promo-contents");this.w=this.A=this.u=null;this.F=new g.H(function(){this.u.setAttribute("aria-hidden",!0);g.wh(this.A,!1);g.wh(this.w,!0)},700,this);
g.B(this,this.F)},asa=function(a){var b=a.annotation.data;
if("cta"==a.annotation.style)var c=6;else if("video"==a.annotation.style||"playlist"==a.annotation.style)c=7;a.G=b.collapse_delay_ms||a.G;var d=["iv-promo","iv-promo-inactive"];a.o.setAttribute("aria-hidden",!0);a.o.setAttribute("aria-label","Promotion");a.o.tabIndex=0;var e=a.annotation.Vb(),f=b.image_url;if(f){var k=g.Vd("DIV",["iv-promo-img","iv-click-target"]);f=g.Vd("IMG",{src:f,"aria-hidden":"true"});k.appendChild(f);b.video_duration&&!b.is_live?(f=g.Vd("SPAN","iv-promo-video-duration",b.video_duration),
k.appendChild(f)):b.playlist_length&&(f=g.Vd("SPAN","iv-promo-playlist-length",b.playlist_length.toString()),k.appendChild(f));e&&a.kk(k,e,a.annotation.id,b.session_data,void 0,c)}e?(f=g.Vd("A","iv-promo-txt"),g.Fc(f,a3(e)),a.u=f):a.u=g.Vd("DIV","iv-promo-txt");switch(a.annotation.style){case "cta":case "website":var l=g.Vd("P",null,g.Vd("STRONG",null,b.text_line_1));var m=g.Vd("P",null,g.Vd("SPAN","iv-promo-link",b.text_line_2));if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");g.R(a.context.A.experiments,
"web_action_cta_larger_ui")&&d.push("iv-promo-website-card-cta-larger-ui");var n=g.Vd("BUTTON",["iv-promo-round-expand-icon","ytp-button"]);f=g.Vd("BUTTON",["iv-button","iv-promo-button"],g.Vd("SPAN","iv-button-content",f));var p=g.Vd("DIV","iv-promo-button-container");p.appendChild(f);e&&a.kk(a.o,e,a.annotation.id,b.session_data,void 0,c)}g.I(a.u,"iv-click-target");e&&a.kk(a.u,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=g.Vd("P",null,g.Vd("SPAN",null,b.text_line_1)),
m=g.Vd("P",null,g.Vd("STRONG",null,b.text_line_2)),b.is_live&&(l=m,m=g.Vd("SPAN",["yt-badge","iv-promo-badge-live"],"LIVE NOW")),g.I(a.u,"iv-click-target"),e&&a.kk(a.u,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.u.appendChild(l);m&&a.u.appendChild(m);a.H.appendChild(a.u);p&&a.H.appendChild(p);c=g.Vd("DIV","iv-promo-actions");a.w=g.Vd("BUTTON",["iv-promo-expand","ytp-button"]);a.w.title="Expand";a.context.o.ia(a.w,"click",g.Ta(a.Vr,5E3),a);c.appendChild(a.w);g.wh(a.w,!1);
a.context.o.ia(a.o,"mouseover",a.JF,a);a.context.o.ia(a.o,"mouseout",a.IF,a);a.context.o.ia(a.o,"touchend",g.Ta(a.Vr,5E3),a);a.A=g.Vd("BUTTON",["iv-promo-close","ytp-button"]);a.A.title="Close";a.context.o.ia(a.A,"click","cta"==a.annotation.style&&b.text_line_3?a.BF:a.AF,a);c.appendChild(a.A);g.qn(a.o,d);k&&(a.o.appendChild(k),n&&k.appendChild(n));a.o.appendChild(a.H);a.o.appendChild(c)},bsa=function(a){a.C||a.J||a.B||(g.I(a.o,"iv-promo-collapsed"),a.C=!0,a.F.start())},csa=function(a){a.F.stop();
a.C&&(g.sn(a.o,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.C=!1,a.u&&a.u.removeAttribute("aria-hidden"),g.wh(a.w,!1),g.wh(a.A,!0))},dsa=function(a,b){a.B||(a.B=g.Af(function(){w3(this);
bsa(this)},b,a))},w3=function(a){a.B&&(g.v.clearTimeout(a.B),a.B=null)},x3=function(a){g.KK.call(this,a);
this.J=!1;this.H=0;this.F={};this.T=new Fra(a);this.B=new g.O(this);g.B(this,this.B);this.C=this.w=null;this.B.L(this.player,"onVideoAreaChange",(0,g.w)(this.P,this,"onVideoAreaChange"));this.B.L(this.player,"onHideControls",(0,g.w)(this.P,this,"onHideControls"));this.B.L(this.player,"onShowControls",(0,g.w)(this.P,this,"onShowControls"));this.B.L(this.player,"resize",(0,g.w)(this.P,this,"resize"));this.B.L(this.player,"presentingplayerstatechange",(0,g.w)(this.P,this,"presentingplayerstatechange"));
this.subscribe("presentingplayerstatechange",this.qM,this);this.subscribe("resize",this.xp,this);this.player.N().F.subscribe("vast_info_card_add",this.gB,this);this.R=new g.O(this);g.B(this,this.R);this.V=g.Vd("DIV","video-custom-annotations");this.u=new g.Q({D:"div",Y:["ytp-player-content","ytp-iv-player-content"]});g.B(this,this.u);g.xK(this.player,this.u.element,4);this.u.hide();this.A=new g.Q({D:"div",Y:["ytp-iv-video-content"]});g.B(this,this.A);g.Zd(this.A.element,g.Vd("DIV","video-annotations",
this.V));this.G=this.o=null;this.M=[];esa(this)&&this.load();var b=g.Xd("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.ne(this,function(){g.be(b)});
if(a=b.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},fsa=function(){var a=g.Vd("DIV",["annotation",
"annotation-type-custom"]);g.wh(a,!1);return a},gsa=function(a){switch(a){case "annotation-editor":case "live-dashboard":return!0}return!1},esa=function(a){var b=a.player.N();
a=a.player.getVideoData();return 1==(b.annotationsLoadPolicy||a.annotationsLoadPolicy)&&!a.TC||b.F.get(a.videoId)||g.cB(a)||g.dB(a)?!0:!1},hsa=function(a,b,c){a.J=!0;
a.C=g.bq(b,c)},isa=function(a,b){for(var c={},d=0;d<b.attributes.length;d++){var e=b.attributes[d];
c[e.name]=e.nodeValue}for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Qa(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"==e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"==typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"==e.tagName?1==e.childNodes.length&&3==e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(isa(a,e))}return c},jsa=function(a,b,c){return!(a.loaded&&a.H==b&&a.player.getVideoData().videoId==
c)},msa=function(a){var b=a.player.getVideoData();
if(b.ge){var c=a.player.N().F.get(b.videoId);if(c){var d={format:"XML",ee:{},method:"POST",withCredentials:!0};d.md=(0,g.w)(function(e,f,k){jsa(this,e,f)||(e=g.Wp(k)&&k.responseXML?k.responseXML:null)&&y3(this,e)},a,a.H,b.videoId);
g.tp()&&(d.md=ksa(a,d.md));d.vb={ic_only:"1"};lsa(d,c);a.J=!0;g.bq(b.ge,d)}}},lsa=function(a,b){a.method="POST";
a.vb=a.vb||{};b.Fn&&(a.vb.ic_coll=b.Fn);b.Gn&&(a.vb.ic_xml=b.Gn);b.Om&&(a.vb.ic_track=b.Om)},nsa=function(a){var b=new g.Q({D:"div"});
g.wh(b.element,!1);var c=new n3(a.player,b.element,z3(a));g.B(c,b);b.ba(a.u.element);c.Dm();return c},z3=function(a){if(!a.G){var b=new M2(a);
g.B(a,b);var c=new g.L1(a);g.B(a,c);a.G=new Hra(b,c,a.player.N(),a.player.getVideoData(),a.T,a.player,a.Fh)}return a.G},y3=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.Ar();if(e){var f=g.yr();f&&g.Pr(g.io("use_default_events_client")?void 0:g.nq,e,f,[g.sr(d)])}}d=b.getElementsByTagName("annotation");for(e=0;e<d.length;e++){var k=isa(a,d[e]);f=null;try{if(k){var l=k.id,m=/.+/;var n="string"===typeof l&&null!=m&&null!=l&&l.match(m)?l:"";var p=Z2(k.type,osa),t=Z2(k.style,psa),u=Y2(k.data),z=0!=u.length?JSON.parse(u):{},D=vra(k.action);f=n&&p?new b3(n,p,t,D,z):null}else f=null}catch(ma){}if(f){a:{switch(f.type){case "branding":case "promotion":k=
!0;break a}k=!1}if(k){k=a;m=f;var E=fsa(),F=null;switch(m.type){case "branding":if(k.player.N().sa)break;k.u.element.appendChild(E);F=new u3(E,z3(k),m);break;case "promotion":g.xK(k.player,E,4),F=new v3(E,z3(k),m)}F&&F.Dm();if(k=F)g.B(a,k),a.F[f.id]=k}else if("card"==f.type||"drawer"==f.type){a.o||(a.o=nsa(a),g.B(a,a.o));if("card"==f.type){if(c=a.o,F=f&&f.data&&f.data.card_type)switch(k=f.data.tracking||{},k={Rx:k.impression,click:k.click,close:k.close,qC:k.teaser_impression,fq:k.teaser_click},m=
f.data.tracking_params||{},E=null,F){case "collaborator":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Ob:f.data.session_data||{},sponsored:f.data.sponsored||!1,Nc:k,je:m.card?g.sr(m.card):null,ce:m.teaser?g.sr(m.teaser):null,Dd:m.icon?g.sr(m.icon):null,channelId:f.data.channel_id,customMessage:f.data.custom_message?f.data.custom_message:null,vB:f.data.image_url,
title:f.data.title,metaInfo:f.data.meta_info,url:$2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};q3(c,f);break;case "episode":case "movie":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Ob:f.data.session_data||{},sponsored:f.data.sponsored||!1,Nc:k,je:m.card?g.sr(m.card):null,ce:m.teaser?g.sr(m.teaser):null,
Dd:m.icon?g.sr(m.icon):null,cj:f.data.image_url,cw:f.data.badge_symbol||"",priceText:f.data.price_text||"",title:f.data.title,metaInfo:f.data.meta_info,sG:!!f.data.is_paygated,pP:!!f.data.user_has_entitlement,url:$2({target:f.data.target||"new",value:f.data.url})};q3(c,f);break;case "playlist":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Ob:f.data.session_data||
{},sponsored:f.data.sponsored||!1,Nc:k,je:m.card?g.sr(m.card):null,ce:m.teaser?g.sr(m.teaser):null,Dd:m.icon?g.sr(m.icon):null,cj:f.data.image_url,playlistVideoCount:f.data.playlist_video_count,customMessage:f.data.custom_message?f.data.custom_message:null,title:f.data.title,metaInfo:f.data.meta_info,url:$2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};q3(c,f);break;case "poll":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,
teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Ob:f.data.session_data||{},sponsored:f.data.sponsored||!1,Nc:k,je:m.card?g.sr(m.card):null,ce:m.teaser?g.sr(m.teaser):null,Dd:m.icon?g.sr(m.icon):null,title:f.data.title,choices:f.data.choices,He:f.data.hasOwnProperty("old_vote")?f.data.old_vote:null,Xi:f.data.signin_url?$2({target:"current",value:f.data.signin_url}):null,AP:f.data.hasOwnProperty("xsrf_token")?f.data.xsrf_token:null};q3(c,f);break;case "productListing":f.data.signin_url&&
(E=$2({target:"current",value:f.data.signin_url}));F=[];for(var G=f.data.offers||[],K=0;K<G.length;K++)F.push(new Era(g.Oc(G[K].merchant),g.Oc(G[K].price)));f={KT:!1,id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Ob:f.data.session_data||{},sponsored:f.data.sponsored||!1,Nc:k,je:m.card?g.sr(m.card):null,ce:m.teaser?g.sr(m.teaser):null,Dd:m.icon?g.sr(m.icon):null,
imageUrl:f.data.image_url,displayDomain:f.data.display_domain?f.data.display_domain:null,showLinkIcon:!!f.data.show_link_icon,yn:f.data.button_icon_url?f.data.button_icon_url:null,title:f.data.title,customMessage:f.data.custom_message?f.data.custom_message:null,url:$2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url}),Xi:E,lU:f.data.signin_title?f.data.signin_title:null,kU:f.data.signin_message?f.data.signin_message:null,offers:F};q3(c,f);break;case "simple":f=
{id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Ob:f.data.session_data||{},sponsored:f.data.sponsored||!1,Nc:k,je:m.card?g.sr(m.card):null,ce:m.teaser?g.sr(m.teaser):null,Dd:m.icon?g.sr(m.icon):null,imageUrl:f.data.image_url,displayDomain:f.data.display_domain?f.data.display_domain:null,showLinkIcon:!!f.data.show_link_icon,yn:f.data.button_icon_url?f.data.button_icon_url:
null,title:f.data.title,customMessage:f.data.custom_message?f.data.custom_message:null,url:$2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};q3(c,f);break;case "video":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Ob:f.data.session_data||{},sponsored:f.data.sponsored||!1,Nc:k,je:m.card?g.sr(m.card):null,ce:m.teaser?
g.sr(m.teaser):null,Dd:m.icon?g.sr(m.icon):null,cj:f.data.image_url,videoDuration:f.data.video_duration||null,customMessage:f.data.custom_message?f.data.custom_message:null,title:f.data.title,metaInfo:f.data.meta_info,isLiveNow:!!f.data.is_live_now,url:$2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})},q3(c,f)}}else Rra(a.o,f);c=!0}}}c&&(D2(a.player),a.xp())},qsa=function(a,b){var c=!1;
a.o||(a.o=nsa(a),g.B(a,a.o));for(var d=g.q(b.cards||[]),e=d.next();!e.done;e=d.next())Sra(a.o,e.value.cardRenderer),c=!0;c&&(c=a.o,d=b.headerText?g.U(b.headerText):"",g.fe(c.Ba,d),c.R&&c.R.setAttribute("title",d),c.ca=b.trackingParams?g.sr(b.trackingParams):null,c.V=b.closeButton.infoCardIconRenderer.trackingParams?g.sr(b.closeButton.infoCardIconRenderer.trackingParams):null,c.J=b.icon.infoCardIconRenderer.trackingParams?g.sr(b.icon.infoCardIconRenderer.trackingParams):null,D2(a.player),a.xp())},
rsa=function(a,b,c,d,e){if(!a.player.N().sa){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new zra("openUrl","click",new xra("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0),null));var k=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:k.height,image_type:1,image_url:k.url,image_width:k.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;b=b.subscribeButton.subscribeButtonRenderer;k=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.U(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(k=g.U(b.subscriberCountText))):(b.subscriberCountText&&(e=g.U(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(k=g.U(b.subscriberCountWithSubscribeText)));var l="";b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url&&(l=b.signInEndpoint.webNavigationEndpointData.url);b={subscribeText:g.U(b.unsubscribedButtonText),subscribeCount:e,unsubscribeText:g.U(b.subscribedButtonText),unsubscribeCount:k,enabled:b.enabled,classic:!1,subscribed:b.subscribed,feature:"iv",signInUrl:l};d.standalone_subscribe_button_data=b}f=new b3(c,"branding","branding",f,d);d=fsa();a.u.element.appendChild(d);f=new u3(d,z3(a),f);f.Dm();g.B(f,f);a.F[c]=f}},ksa=function(a,b){return(0,g.w)(function(){if(!this.ga()){var c=
Array.prototype.slice.call(arguments,0);
c.unshift(b);b=g.Ta.apply(window,c);this.M.push(g.rp(b))}},a)},G2={},H2=null;g.Va(J2,g.tn);g.h=J2.prototype;g.h.getDuration=function(){return this.duration};
g.h.play=function(a){if(a||0==this.o)this.progress=0,this.coords=this.w;else if(this.Ya())return!1;I2(this);this.startTime=a=(0,g.C)();-1==this.o&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.B=this.startTime;this.progress||this.tp();this.ye("play");-1==this.o&&this.ye("resume");this.o=1;var b=g.Sa(this);b in G2||(G2[b]=this);gra();hra(this,a);return!0};
g.h.stop=function(a){I2(this);this.o=0;a&&(this.progress=1);ira(this,this.progress);this.ye("stop");this.lm()};
g.h.pause=function(){this.Ya()&&(I2(this),this.o=-1,this.ye("pause"))};
g.h.X=function(){0==this.o||this.stop(!1);this.ye("destroy");J2.Fb.X.call(this)};
g.h.destroy=function(){this.dispose()};
g.h.Pt=function(){this.ye("animate")};
g.h.ye=function(a){this.dispatchEvent(new jra(a,this))};
g.Va(jra,g.qe);g.Va(K2,J2);K2.prototype.A=g.Ka;K2.prototype.Pt=function(){this.A();K2.Fb.Pt.call(this)};
K2.prototype.lm=function(){this.A();K2.Fb.lm.call(this)};
K2.prototype.tp=function(){this.A();K2.Fb.tp.call(this)};
g.Va(L2,K2);L2.prototype.A=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.r(M2,g.A);M2.prototype.ia=function(a,b,c,d){c=(0,g.w)(c,d||this.u);a=g.cp(a,b,c);this.o.push(a);return a};
M2.prototype.Gs=function(a,b,c,d){c=(0,g.w)(c,d||this.u);a=g.mp(a,b,c);this.o.push(a);return a};
M2.prototype.Va=function(a){g.dp(a);g.gb(this.o,a)};
M2.prototype.X=function(){g.dp(this.o);this.o.length=0;g.A.prototype.X.call(this)};g.r(Q2,g.KK);g.h=Q2.prototype;g.h.load=function(){g.KK.prototype.load.call(this);if(!R2(this)){var a=g.bB(this.player.getVideoData());if(a)a=P2(a,mra(this)),S2(this,a,!1);else{var b=this.player.getVideoData();a=b.videoId;this.A&&this.A.abort();a={method:"POST",md:(0,g.w)(this.gL,this,a),ee:{v:a},withCredentials:!0};this.J&&(a.ee.ptype="embedded");var c=this.player.getVideoData().Rn;c&&(a.vb={ad_tracking:c});if(b=g.aB(b))if(b=g.cc(b),b=g.ac(b))this.A=g.bq(b,a)}}};
g.h.unload=function(){S2(this,null);this.A&&(this.A.abort(),this.A=null);g.KK.prototype.unload.call(this)};
g.h.Qc=function(a,b){if(!R2(this))return null;if("loadCustomEndscreenRenderer"==a){var c=P2(b,"new");S2(this,c);return!0}return null};
g.h.getOptions=function(){return R2(this)?["loadCustomEndscreenRenderer"]:[]};
g.h.gL=function(a,b){var c=this.A=null;if(200==b.status){var d=b.responseText;")]}"==d.substring(0,3)&&(d=d.substring(3),c=JSON.parse(d),c=P2(c,mra(this)))}S2(this,c)};
g.h.Qy=function(){if(this.u&&this.u.elements){var a=this.player.getVideoContentRect();if(a&&0!=a.width&&0!=a.height){var b=this.player.getPlayerSize();if(b&&0!=b.width&&0!=b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<ssa.length;f++){var k=Math.abs(b.width-ssa[f]);if(-1==e||d>=k)e=f,d=k}d=tsa[e];this.w&&g.ch(this.w.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.u.elements.length;++b)if(f=this.u.elements[b].id,e=this.o[f],k=this.F[f],e&&k){var l=k.width*c/k.aspectRatio;
f=Math.round(l*a.height);var m=a.left+Math.round(k.left*a.width),n=a.top+Math.round(k.top*a.height);g.uh(e.element,Math.round(k.width*a.width),f);g.kh(e.element,m,n);g.sn(e.element,usa);m=k.left+k.width/2;k=k.top+l/2;g.I(e.element,.5>=m&&.5>=k?"ytp-ce-top-left-quad":.5<m&&.5>=k?"ytp-ce-top-right-quad":.5>=m&&.5<k?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.sn(e.element,tsa);g.I(e.element,d);(e=g.Id(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.ch(e,"height",f+"px")}}}}};
g.h.hH=function(a){if(this.u)if("ytp-ce-in-endscreen"==a.getId())W2(this,this.u.impressionUrls),(a=g.Ar())&&this.u.visualElement&&g.Qr(a,this.u.visualElement);else{a=a.getId().substring(15);var b=this.o[a],c=this.F[a];g.I(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");g.I(g.cK(this.player),"ytp-ce-shown");W2(this,c.impressionUrls);(b=g.Ar())&&g.Qr(b,c.visualElement);this.player.N().Eb&&this.player.ma("endscreenelementshown",a)}};
g.h.iH=function(a){if("ytp-ce-in-endscreen"!=a.getId()){a=a.getId().substring(15);var b=this.o[a];g.rn(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden",!0);g.rn(g.cK(this.player),"ytp-ce-shown");this.player.N().Eb&&this.player.ma("endscreenelementhidden",a)}};
g.h.TN=function(a){var b=this;a.target===window&&(new g.H(function(){for(var c in b.o)g.sn(b.o[c].element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.h.xA=function(a,b){if(a.targetUrl&&(!b||"keypress"!=b.type||13==b.keyCode)){for(var c=b.target;c&&!g.pn(c,"ytp-ce-element");){g.pn(c,"subscribe-label")&&X2(this,a);if(g.pn(c,"ytp-ce-channel-subscribe"))return;c=g.de(c)}if(!c||g.pn(c,"ytp-ce-element-hover")){b.preventDefault();b.stopPropagation();if(c=this.o[a.id])this.Tt(c,a),c.element.blur();b.ctrlKey||b.metaKey||"new"==a.WO?(X2(this,a),this.ZB(),this.player.pauseVideo(),c=g.cc(U2(this,a.targetUrl)),c=g.ac(c),g.PL(c,void 0,a.Ob)):(c=this.player.getVideoData().Dc,
c=(0,g.w)(this.PO,this,c,U2(this,a.targetUrl),a.Ob),c=(0,g.w)(this.ZB,this,c),X2(this,a,c))}}};
g.h.PO=function(a,b,c){var d=g.Kp(b);a&&d&&(d.v||d.list)?g.FS(this.player.app,d.v,c,d.list,!1,void 0):g.OL(b,c)};
g.h.Ss=function(a,b){g.pn(a.element,"ytp-ce-element-hover")||("VIDEO"==b.type||"PLAYLIST"==b.type?g.I(a.element,"ytp-ce-element-hover"):this.player.N().o?(new g.H(function(){g.I(a.element,"ytp-ce-element-hover")},200)).start():g.I(a.element,"ytp-ce-element-hover"),W2(this,b.gG),V2(this,b.id,!0))};
g.h.Tt=function(a,b){g.rn(a.element,"ytp-ce-element-hover");g.rn(a.element,"ytp-ce-force-expand");V2(this,b.id,!1)};
g.h.ZB=function(a){this.player.sendVideoStatsEngageEvent(17,a)};
var ssa=[346,426,470,506,570,640,853,1280,1920],tsa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),usa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var yra={FQ:"current",cS:"new"};var Ara={CLOSE:"close",fS:"openUrl",QD:"subscribe"},Bra={zQ:"click",CLOSE:"close",sR:"hidden",KS:"rollOut",LS:"rollOver",OS:"shown"};b3.prototype.Vb=function(){var a=Cra(this,function(b){return"openUrl"==b.type&&null!=b.url});
return a?a.url:null};
var psa={cQ:"anchored",kD:"branding",CHANNEL:"channel",EQ:"cta",uR:"highlightText",LR:"label",PLAYLIST:"playlist",xS:"popup",SS:"speech",QD:"subscribe",dT:"title",VIDEO:"video",qT:"website"},osa={kD:"branding",qQ:"card",MQ:"drawer",tR:"highlight",SR:"marker",CS:"promotion",TEXT:"text",sT:"widget"};d3.prototype.u=function(a,b){var c=g.ke(b.target,"label");c&&g.J(c,"iv-card-poll-choice-focused",a)};
d3.prototype.A=function(a,b){var c=g.ke(b.target,null,"iv-card-poll",void 0);if(c)if(a.Xi)g.Kd("iv-card-sign-in-button",c).click();else{var d=parseInt(cra(b.target),10);if(null==a.He)a.choices[d].count++,a.He=d;else if(a.He!=d){var e=a.choices[a.He];e.count=Math.max(e.count-1,0);a.choices[d].count++;a.He=d}else e=a.choices[a.He],e.count=Math.max(e.count-1,0),a.He=null;Jra(a,c);g.fq(this.o.videoData.ge,{ee:{action_poll_vote:1},vb:{poll_id:a.id,index:d,session_token:a.AP}});c3(this.o.logger,a.Nc.click,
void 0,5);(c=g.Ar())&&a.je&&g.Rr(c,a.je)}};g.r(j3,g.A);g.h=j3.prototype;g.h.addCueRange=function(a,b,c,d,e){a=new g.HC(a,b,{id:c});a.namespace="annotations_module";d&&this.na.set(a,d);e&&this.ra.set(a,e);g.tK(this.context.U,[a])};
g.h.Dm=function(){this.context.u.subscribe("resize",this.Bn,this)};
g.h.kk=function(a,b,c,d,e,f){this.context.o.ia(a,"click",g.Ta(this.Ho,b,c,d,e||[],f||0),this);this.context.o.ia(a,"touchstart",g.Ta(function(){this.Vu=!1}),this);
this.context.o.ia(a,"touchmove",g.Ta(function(){this.Vu=!0}),this)};
g.h.Ho=function(a,b,c,d,e,f){if(this.Vu)return!1;f&&(f.stopPropagation(),f.preventDefault());Pra(this,a,c,d,e);return!1};
g.h.show=function(){};
g.h.hide=function(){};
g.h.destroy=function(){g.be(this.o)};
g.h.Bn=function(){};
g.h.X=function(){this.na.clear();this.ra.clear();g.A.prototype.X.call(this)};g.r(n3,j3);g.h=n3.prototype;g.h.isAvailable=function(){var a;if(a=!!this.A.length)(a=g.cK(this.w))?(a=g.vh(a),a=173<a.width&&173<a.height):a=!1;return a};
g.h.Bn=function(){var a=this.isAvailable();g.wh(this.o,a);g.J(g.cK(this.context.U),"ytp-iv-drawer-enabled",a);D2(this.w)};
g.h.destroy=function(){var a=g.lK(g.YJ(this.w));a&&a.Os(!1,void 0);try{g.cK(this.w).removeChild(this.F)}catch(b){}g.Ao(this.Z);g.dp(this.ea);this.ha&&this.ha.dispose();this.G&&this.G.dispose();j3.prototype.destroy.call(this)};
g.h.vH=function(a){this.aa.start();a.preventDefault();a=a||window.event;var b=0;"MozMousePixelScroll"==a.type?b=0==(a.axis==a.HORIZONTAL_AXIS)?a.detail:0:window.opera?b=a.detail:b=0==a.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?a.wheelDeltaY/-30:a.wheelDeltaY/-1.2:a.wheelDelta/-1.6:a.wheelDeltaY/-3;if(a=b)this.B.scrollTop+=a};
g.h.aC=function(a){if(!g.pn(g.cK(this.w),"ytp-cards-teaser-shown")){if(this.u!=a){var b=g.Ar(),c=this.u?this.u.card.Dd:this.J;b&&c&&F2(b,[c]);this.u=a;r3(this)}if(b="none"!=this.o.style.display)2==this.context.U.getPresentingPlayerType()?b=1==this.context.U.getAdState():(b=this.context.U.getPlayerState(),c=0==b&&0===this.context.U.getCurrentTime(),b=1==b||3==b||c);b&&a.card.teaserDurationMs&&(b={teaserText:a.card.teaserText,durationMs:a.card.teaserDurationMs},(c=g.lK(g.YJ(this.w)))&&c.Os(!0,b));this.ya.isActive()||
((!this.C||!this.aa.isActive()&&this.da)&&Zra(this,a),this.ya.start(910+a.card.teaserDurationMs))}};
g.h.GO=function(a){this.C||(this.u=a,r3(this),Zra(this,a),l3(this,"YOUTUBE_DRAWER_AUTO_OPEN",!1))};
g.h.vE=function(){if(this.C){c3(this.context.logger,s3(this).Nc.close);var a=g.Ar();a&&this.V&&g.Rr(a,this.V);m3(this)}};
g.h.LE=function(){g.J(this.F,"iv-drawer-scrolled",0<this.B.scrollTop)};
g.h.AG=function(){var a=g.Ar(),b=s3(this);b=b?b.Dd:this.J;a&&b&&E2(a,[b])};
g.h.zG=function(){var a=g.Ar(),b=s3(this);b=b?b.Dd:this.J;a&&b&&F2(a,[b])};
g.h.DG=function(){var a=s3(this);c3(this.context.logger,a.Nc.qC);var b=g.Ar();b&&a&&E2(b,[a.ce,a.Dd])};
g.h.CG=function(){var a=g.Ar(),b=s3(this);a&&b&&F2(a,[b.ce])};
g.h.BG=function(a){var b=s3(this),c=g.Ar();this.u?a?(a=this.context.logger,c3(a,b.Nc.fq),a.o.sendVideoStatsEngageEvent(4,void 0),c&&b.ce&&g.Rr(c,b.ce)):(a=this.context.logger,c3(a,b.Nc.fq),a.o.sendVideoStatsEngageEvent(4,void 0),c&&b.Dd&&g.Rr(c,b.Dd)):(a=this.context.logger,c3(a,b.Nc.fq),a.o.sendVideoStatsEngageEvent(4,void 0),c&&this.J&&g.Rr(c,this.J))};g.r(t3,j3);t3.prototype.Dm=function(){j3.prototype.Dm.call(this);$ra(this)};
t3.prototype.show=function(){j3.prototype.show.call(this);var a=g.Ar(),b=this.annotation.data;a&&b&&(b=b.session_data)&&E2(a,[g.sr(b.itct)])};
t3.prototype.hide=function(){j3.prototype.hide.call(this);var a=g.Ar(),b=this.annotation.data;a&&b&&(b=b.session_data)&&F2(a,[g.sr(b.itct)])};g.r(u3,t3);g.h=u3.prototype;g.h.QO=function(a,b,c,d){this.A.stop();if(!this.B){var e=g.vh(a);this.u||(g.th(a,e.width),g.th(b,e.width));g.ch(c,"top",e.height-Math.max(Math.min(e.height,d)/2+10,20)+"px");g.ch(c,"right","1px");this.B=!0;g.wh(a,!0);this.C=new g.H(function(){g.I(this.o,"iv-branding-active")},0,this);
this.C.start()}};
g.h.fG=function(a,b){g.rn(this.o,"iv-branding-active");this.F=new g.H((0,g.w)(function(){g.wh(a,!1);this.u||g.th(b,0)},this),250);
this.F.start();this.B=!1};
g.h.show=function(){if(!this.isActive){t3.prototype.show.call(this);if(!this.G){g.I(this.o,"iv-branding");var a=this.annotation.data;this.w=g.Vd("IMG",{"aria-label":"Channel watermark",src:a.image_url,"class":"branding-img iv-click-target",width:a.image_width,height:a.image_height});g.wh(this.w,!1);var b=g.Vd("DIV","branding-img-container",this.w);this.o.appendChild(b);(b=this.annotation.Vb())&&this.kk(this.w,b,this.annotation.id,a.session_data);if(a.channel_name){var c=g.Vd("DIV","iv-branding-context-name");
g.fe(c,a.channel_name);var d=g.Vd("DIV","iv-branding-context-subscribe");if(b=a.standalone_subscribe_button_data)this.u=new g.aP(b.subscribeText,b.subscribeCount,b.unsubscribeText,b.unsubscribeCount,!!b.enabled,!!b.classic,a.channel_id,!!b.subscribed,b.feature,a.session_data.itct,b.signinUrl,this.context.U),this.u.ba(d);b=g.Vd("DIV","iv-branding-context-subscribe-caret");c=g.Vd("DIV","branding-context-container-inner",b,c,d);g.wh(c,!1);d=g.Vd("DIV","branding-context-container-outer",c);g.ch(d,"right",
a.image_width+"px");this.o.appendChild(d);this.A=new g.H(g.Ta(this.fG,c,d),500,this);g.B(this,this.A);this.context.o.ia(this.o,"mouseover",(0,g.w)(this.QO,this,c,d,b,a.image_height));this.context.o.ia(this.o,"mouseout",(0,g.w)(this.A.start,this.A,void 0))}this.G=!0}g.wh(this.o,!0);this.isActive=!0;if(this.w){a=this.w;var e=void 0===e?0:e;b=g.oh(a);c=g.vh(a);b=(new g.$g(b.x,b.y,c.width,c.height)).width;g.kh(a,b);e=new L2(a,[b,a.offsetTop],[b-b-e,a.offsetTop],200,dra);g.B(this,e);this.context.w.ia(e,
"begin",g.Ta(g.wh,a,!0));e.play()}}};
g.h.hide=function(){this.isActive&&(t3.prototype.hide.call(this),g.wh(this.o,!1),this.isActive=!1)};
g.h.destroy=function(){this.u&&(this.u.dispose(),this.u=null);t3.prototype.destroy.call(this)};g.r(v3,t3);g.h=v3.prototype;g.h.show=function(){this.isActive||(t3.prototype.show.call(this),this.M||(asa(this),this.M=!0),g.wh(this.o,!0),g.Af(function(){g.rn(this.o,"iv-promo-inactive")},100,this),this.o.removeAttribute("aria-hidden"),this.isActive=!0,w3(this),csa(this),dsa(this,this.G))};
g.h.hide=function(){this.isActive&&(g.I(this.o,"iv-promo-inactive"),this.isActive=!1,this.o.setAttribute("aria-hidden",!0))};
g.h.Ho=function(a,b,c,d,e,f){return this.C?!1:t3.prototype.Ho.call(this,a,b,c,d,e,f)};
g.h.Vr=function(a,b){b.stopPropagation();csa(this);dsa(this,a);this.u.focus()};
g.h.JF=function(a){this.J=!0;this.Vr(500,a)};
g.h.IF=function(){this.J=!1;bsa(this)};
g.h.AF=function(a){a.stopPropagation();this.hide()};
g.h.BF=function(a){a.stopPropagation();w3(this);this.C=!0;g.I(this.o,"iv-promo-collapsed-no-delay");this.F.start()};
g.h.destroy=function(){this.F.dispose();t3.prototype.destroy.call(this)};g.r(x3,g.KK);g.h=x3.prototype;g.h.Qc=function(a,b){if(!gsa(this.player.N().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.K1(b);c&&y3(this,c);return!0;case "removeCustomAnnotationById":return b&&this.o&&(Ura(this.o,b),D2(this.player)),!0}return null};
g.h.getOptions=function(){return gsa(this.player.N().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.h.xp=function(){if(this.A){var a=g.bK(this.player).getVideoContentRect(!0);g.uh(this.A.element,a.width,a.height);g.kh(this.A.element,a.left,a.top)}if(this.o){var b=g.oK(this.player);a=this.o;b=b.width;g.J(a.F,"iv-drawer-small",426>=b);g.J(a.F,"iv-drawer-big",1280<=b)}};
g.h.qM=function(a){this.zc(a.state);g.V(a.state,2)&&(this.Ml()&&this.Fy()&&2!=this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Os(!1))};
g.h.load=function(){g.KK.prototype.load.call(this);this.zc(g.eK(this.player));this.H++;var a=this.player.getVideoData(),b=a.videoId,c=(0,g.w)(this.iL,this,b,this.H),d=(0,g.w)(function(){this.C=null},this);
g.tp()&&(c=ksa(this,c));c={format:"XML",md:c,onError:d,ee:{}};a.isPharma&&(c.ee.pharma="1");c.method="POST";c.withCredentials=!0;(b=this.player.N().F.get(b))&&lsa(c,b);b=b&&(b.Gn||b.Fn);if(!a.pn||b)a.ge?hsa(this,a.ge,c):(this.w=(0,g.w)(this.fH,this,c),this.player.addEventListener("videodatachange",this.w));g.xK(this.player,this.A.element,4);this.xp();(b=g.cB(a))&&qsa(this,b);(b=g.dB(a))&&b.featuredChannel&&rsa(this,b.featuredChannel,b.annotationId||"branding",a.videoId||null,a.eventId||null)};
g.h.zc=function(a){a=!a.isCued()&&!g.V(a,1024);g.Ws(this.u,a);g.Ws(this.A,a)};
g.h.fH=function(a){var b=this.player.getVideoData();b.ge&&(this.w&&(this.player.removeEventListener("videodatachange",this.w),this.w=null),hsa(this,b.ge,a))};
g.h.unload=function(){g.MP(this.player.app,"annotations_module",void 0);g.y.forEach(this.F,function(a){a.destroy()});
this.G=null;this.o&&(this.o.destroy(),this.o=null,D2(this.player));this.J=!1;this.C&&(this.C.abort(),this.C=null);this.F={};this.u.hide();g.KK.prototype.unload.call(this);g.Ts(this.A);this.w&&(this.player.removeEventListener("videodatachange",this.w),this.w=null)};
g.h.iL=function(a,b,c){this.C=null;!jsa(this,b,a)&&(a=g.Wp(c)&&c.responseXML?c.responseXML:null)&&(y3(this,a),g.I(g.cK(this.player),"iv-module-loaded"))};
g.h.gB=function(a){a==this.player.getVideoData().videoId&&(this.loaded?msa(this):this.load())};
g.h.Ml=function(){return!!this.o&&this.o.isAvailable()};
g.h.Fy=function(){this.Ml();return!!this.o&&this.o.C};
g.h.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.Ml();this.o&&(a?c?l3(this.o,c,b):l3(this.o,"YOUTUBE_DRAWER_AUTO_OPEN",b):m3(this.o))};
g.h.Os=function(a,b){this.player.P(a?"cardsteasershow":"cardsteaserhide",b)};
g.h.X=function(){this.player.N().F.unsubscribe("vast_info_card_add",this.gB,this);g.rn(g.cK(this.player),"ytp-iv-drawer-open");for(var a=this.M,b=0,c=a.length;b<c;b++)g.up(a[b]);this.M.length=0;g.KK.prototype.X.call(this)};g.ZK.annotations_module=x3;g.ZK.creatorendscreen=Q2;})(_yt_player);
