(function(g){var window=this;var U4=function(a,b,c){var d=b.va();g.J(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.tc(c?c:"mqdefault.jpg");var f=b instanceof g.uA&&b.lengthSeconds?g.bL(b.lengthSeconds):null,k=!!e;e=k&&"RD"===(new g.LC(e.substr(0,2),e.substr(2))).type;var l=b instanceof g.uA?b.ua:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:b.author,aria_label:b.Gk||g.LL("Watch $TITLE",{TITLE:b.title}),duration:f,url:b.si(),is_live:l,is_list:k,
is_mix:e,background:c?"background-image: url("+c+")":""};b instanceof g.MC&&(d.playlist_length=b.getLength());a.update(d)},V4=function(a){g.Q.call(this,{D:"div",
Y:["ytp-upnext","ytp-player-content"],O:{"aria-label":"{{aria_label}}"},K:[{D:"div",I:"ytp-cued-thumbnail-overlay-image",O:{style:"{{background}}"}},{D:"span",I:"ytp-upnext-top",K:[{D:"span",I:"ytp-upnext-header",W:"Up Next"},{D:"span",I:"ytp-upnext-title",W:"{{title}}"},{D:"span",I:"ytp-upnext-author",W:"{{author}}"}]},{D:"a",I:"ytp-upnext-autoplay-icon",O:{role:"button",href:"{{url}}","aria-label":"Play next video"},K:[{D:"svg",O:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},K:[{D:"circle",
I:"ytp-svg-autoplay-circle",O:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{D:"circle",I:"ytp-svg-autoplay-ring",O:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{D:"path",I:"ytp-svg-fill",O:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{D:"span",I:"ytp-upnext-bottom",K:[{D:"span",I:"ytp-upnext-cancel"},{D:"span",I:"ytp-upnext-paused",W:"Autoplay is paused"}]}]});
this.B=null;var b=this.o["ytp-upnext-cancel"];this.B=new g.Q({D:"button",Y:["ytp-upnext-cancel-button","ytp-button"],O:{tabindex:"0","aria-label":"Cancel autoplay"},W:"Cancel"});g.B(this,this.B);this.B.ia("click",this.FK,this);this.B.ba(b);this.u=a;this.J=this.o["ytp-svg-autoplay-ring"];this.F=this.C=this.w=this.A=null;this.G=new g.H(this.Kn,5E3,this);g.B(this,this.G);this.H=0;g.zK(this.u,this.element,this,18788);this.L(this.o["ytp-upnext-autoplay-icon"],"click",this.lM);this.mA();this.L(a,"autonavvisibility",
this.mA);this.L(a,"mdxnowautoplaying",this.FL);this.L(a,"mdxautoplaycanceled",this.GL);this.L(a,"mdxautoplayupnext",this.MC);3==this.u.getPresentingPlayerType()&&(a=(a=g.fK(g.YJ(this.u)))?a.qF():null)&&this.MC(a);g.J(this.element,"ytp-upnext-mobile",this.u.N().o)},W4=function(a,b){if(!a.w){g.Bo("a11y-announce","Up Next "+a.A.title);
a.H=(0,g.N)();a.w=new g.H((0,g.w)(a.Nq,a,b),25);a.Nq(b);var c=b||g.S(a.u.N().experiments,"autoplay_time")||1E4;a.u.ma("onAutonavCoundownStarted",c)}g.rn(a.element,"ytp-upnext-autoplay-paused")},Y4=function(a){X4(a);
a.H=(0,g.N)();a.Nq();g.I(a.element,"ytp-upnext-autoplay-paused")},X4=function(a){a.w&&(a.w.dispose(),a.w=null)},Z4=function(a,b){g.Q.call(this,{D:"div",
Y:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},Hta=function(a){Z4.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.u=new g.Q({D:"div",I:"ytp-subscribe-card",K:[{D:"img",I:"ytp-author-image",O:{src:b.Md}},{D:"div",I:"ytp-subscribe-card-right",K:[{D:"div",I:"ytp-author-name",W:b.author},{D:"div",I:"html5-subscribe-button-container"}]}]});g.B(this,this.u);this.u.ba(this.element);this.subscribeButton=new g.aP("Subscribe",null,"Unsubscribe",null,!0,!1,b.Lg,b.subscribed,"trailer-endscreen",null,null,a);g.B(this,this.subscribeButton);this.subscribeButton.ba(this.u.o["html5-subscribe-button-container"]);
this.hide()},$4=function(a){var b=a.N(),c=g.tw||g.fh?{style:"will-change: opacity"}:void 0,d=b.u,e=["ytp-videowall-still"];
b.o&&e.push("ytp-videowall-show-text");g.Q.call(this,{D:"a",Y:e,O:{href:"{{url}}",target:d?b.A:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},K:[{D:"div",I:"ytp-videowall-still-image",O:{style:"{{background}}"}},{D:"span",I:"ytp-videowall-still-info",K:[{D:"span",I:"ytp-videowall-still-info-bg",K:[{D:"span",I:"ytp-videowall-still-info-content",O:c,K:[{D:"span",I:"ytp-videowall-still-info-title",W:"{{title}}"},{D:"span",I:"ytp-videowall-still-info-author",
W:"{{author_and_views}}"},{D:"span",I:"ytp-videowall-still-info-live",W:"Live"},{D:"span",I:"ytp-videowall-still-info-duration",W:"{{duration}}"}]}]}]},{D:"span",Y:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],K:[{D:"span",I:"ytp-videowall-still-listlabel-icon"},"Playlist",{D:"span",I:"ytp-videowall-still-listlabel-length",K:[" (",{D:"span",W:"{{playlist_length}}"},")"]}]},{D:"span",Y:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],K:[{D:"span",I:"ytp-videowall-still-listlabel-mix-icon"},
"Mix",{D:"span",I:"ytp-videowall-still-listlabel-length",W:" (50+)"}]}]});this.suggestion=null;this.u=d;this.api=a;this.w=new g.O(this);g.B(this,this.w);this.ia("click",this.onClick);this.ia("keypress",this.B);this.w.L(a,"videodatachange",this.A);g.AK(a,this.element,this);this.A()},a5=function(a){Z4.call(this,a,"videowall-endscreen");
var b=this;this.U=a;this.A=0;this.stills=[];this.B=this.videoData=this.suggestions=null;this.C=this.H=!1;this.G=null;this.w=new g.O(this);g.B(this,this.w);this.F=new g.H(function(){g.I(b.element,"ytp-show-tiles")},0);
g.B(this,this.F);var c=new g.Q({D:"button",Y:["ytp-button","ytp-endscreen-previous"],O:{"aria-label":"Previous"},K:[g.jL()]});g.B(this,c);c.ba(this.element);c.ia("click",this.GH,this);this.table=new g.Ss({D:"div",I:"ytp-endscreen-content"});g.B(this,this.table);this.table.ba(this.element);c=new g.Q({D:"button",Y:["ytp-button","ytp-endscreen-next"],O:{"aria-label":"Next"},K:[g.kL()]});g.B(this,c);c.ba(this.element);c.ia("click",this.FH,this);this.u=new V4(a);g.B(this,this.u);g.xK(this.player,this.u.element,
4);this.hide()},b5=function(a){return g.yK(a.player)&&a.Zv()&&!a.B},Ita=function(a,b){return(0,g.ic)(b.suggestions,function(c){c=g.mN(a.U.N(),c);
g.B(a,c);return c})},c5=function(a){var b=a.Ws();
b!==a.H&&(a.H=b,a.player.P("autonavvisibility"))},d5=function(a){g.KK.call(this,a);
this.endScreen=null;this.listeners=new g.O(this);g.B(this,this.listeners);this.o=a.N();Jta(a)?this.endScreen=new a5(this.player):this.o.Ja?this.endScreen=new Hta(this.player):this.endScreen=new Z4(this.player);g.B(this,this.endScreen);g.xK(this.player,this.endScreen.element,4);this.TB();this.listeners.L(a,"videodatachange",this.TB,this);this.listeners.L(a,g.KC("endscreen"),this.DH,this);this.listeners.L(a,"crx_endscreen",this.XK,this)},Jta=function(a){a=a.N();
return a.Ha&&!a.Ja};
g.r(V4,g.Q);g.h=V4.prototype;g.h.Kn=function(){this.C&&(this.G.stop(),this.Va(this.F),this.F=null,this.C.close(),this.C=null)};
g.h.mA=function(){g.Ws(this,g.ZJ(this.u));g.DK(this.u,this.element,g.ZJ(this.u))};
g.h.cM=function(){window.focus();this.Kn()};
g.h.hide=function(){g.Q.prototype.hide.call(this)};
g.h.Nq=function(a){a=a||g.S(this.u.N().experiments,"autoplay_time")||1E4;var b=Math.min((0,g.N)()-this.H,a);a=Math.min(b/a,1);this.J.setAttribute("stroke-dashoffset",-211*(a+1));1<=a&&3!=this.u.getPresentingPlayerType()?this.select(!0):this.w&&this.w.start()};
g.h.select=function(a){a=void 0===a?!1:a;if(g.R(this.u.N().experiments,"autonav_notifications")&&a&&window.Notification&&document.hasFocus){var b=Notification.permission;"default"==b?Notification.requestPermission():"granted"!=b||document.hasFocus()||(b=this.A.va(),this.Kn(),this.C=new Notification("Up Next",{body:b.title,icon:b.tc()}),this.F=this.L(this.C,"click",this.cM),this.G.start())}X4(this);this.u.nextVideo(!1,a)};
g.h.lM=function(a){!g.ee(this.B.element,g.ep(a))&&g.RL(a,this.u)&&this.select()};
g.h.FK=function(){g.aK(this.u,!0)};
g.h.FL=function(a){this.u.getPresentingPlayerType();this.show();W4(this,a)};
g.h.MC=function(a){this.u.getPresentingPlayerType();this.A&&this.A.va().videoId==a.va().videoId||(this.A=a,U4(this,a,"hqdefault.jpg"))};
g.h.GL=function(){this.u.getPresentingPlayerType();X4(this);this.hide()};
g.h.X=function(){X4(this);this.Kn();g.Q.prototype.X.call(this)};g.r(Z4,g.Q);g.h=Z4.prototype;g.h.create=function(){this.created=!0};
g.h.destroy=function(){this.created=!1};
g.h.Zv=function(){return!1};
g.h.Ws=function(){return!1};
g.h.hy=function(){return!1};g.r(Hta,Z4);g.r($4,g.Q);$4.prototype.select=function(){var a=this.suggestion.va().videoId,b=this.suggestion.getPlaylistId();(g.FS(this.api.app,a,this.suggestion.Ob,b,void 0,void 0)||this.api.fa("web_player_endscreen_double_log_fix_killswitch"))&&g.CK(this.api,this.element)};
$4.prototype.onClick=function(a){g.RL(a,this.api,this.u,this.suggestion.Ob||void 0)&&this.select()};
$4.prototype.B=function(a){switch(a.keyCode){case 13:case 32:g.jp(a)||(this.select(),g.ip(a))}};
$4.prototype.A=function(){var a=this.api.getVideoData(),b=this.api.N();this.u=a.Dc?!1:b.u};g.r(a5,Z4);g.h=a5.prototype;g.h.create=function(){Z4.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.suggestions=Ita(this,a),this.videoData=a);this.Dg();this.w.L(this.player,"appresize",this.Dg);this.w.L(this.player,"onVideoAreaChange",this.Dg);this.w.L(this.player,"videodatachange",this.HH);this.w.L(this.player,"autonavchange",this.Xs);this.w.L(this.player,"autonavcancel",this.EH);a=this.videoData.autonavState;a!==this.G&&this.Xs(a);this.w.L(this.element,"transitionend",this.DN)};
g.h.destroy=function(){g.er(this.w);g.pe(this.stills);this.stills=[];this.suggestions=null;Z4.prototype.destroy.call(this);g.rn(this.element,"ytp-show-tiles");this.F.stop();this.G=this.videoData.autonavState};
g.h.Zv=function(){return 1!==this.videoData.autonavState};
g.h.show=function(){Z4.prototype.show.call(this);g.rn(this.element,"ytp-show-tiles");this.player.N().o?g.gn(this.F):this.F.start();(this.C||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.aK(this.player,!1);b5(this)?(c5(this),2===this.videoData.autonavState?g.R(this.player.N().experiments,"fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.u.select(!0):W4(this.u):3===this.videoData.autonavState&&Y4(this.u)):(g.aK(this.player,!0),c5(this))};
g.h.hide=function(){Z4.prototype.hide.call(this);Y4(this.u);c5(this)};
g.h.DN=function(a){g.ep(a)===this.element&&this.Dg()};
g.h.Dg=function(){if(this.suggestions&&this.suggestions.length){g.I(this.element,"ytp-endscreen-paginate");var a=g.oK(this.U,!0,this.U.isFullscreen()),b=g.xB(this.U);b&&(b=b.wc()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.suggestions.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var p=b/2,t=e/2,u=b<=f-2&&n>=t*m,z=e<=k-2&&n>=p*m;if((p+1)/t*d/c>c/(p/(t+1)*d)&&z)n-=p*m,e+=2;else if(u)n-=
t*m,b+=2;else if(z)n-=p*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.ud(a.width/m||1,1,1.21);n*=g.ud(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.table.element;g.uh(a,m,n);g.ch(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});c=this.u;f=this.suggestions[0];c.A=f;U4(c,f,"hqdefault.jpg");g.J(this.element,"ytp-endscreen-takeover",b5(this));c5(this);m+=4;n+=4;for(f=
c=0;f<b;f++)for(k=0;k<e;k++)if(p=c,t=0,d&&f>=b-2&&k>=e-2?t=1:0===k%2&&0===f%2&&(2>k&&2>f?0===k&&0===f&&(t=2):t=2),p=g.vd(p+this.A,l),0!==t){u=this.stills[c];u||(u=new $4(this.player),this.stills[c]=u,a.appendChild(u.element));z=Math.floor(n*k/e);var D=Math.floor(m*f/b),E=Math.floor(n*(k+t)/e)-z-4,F=Math.floor(m*(f+t)/b)-D-4;g.kh(u.element,D,z);g.uh(u.element,F,E);g.ch(u.element,"transitionDelay",(k+f)/20+"s");g.J(u.element,"ytp-videowall-still-mini",1===t);g.J(u.element,"ytp-videowall-still-large",
2<t);t=u;p=this.suggestions[p];t.suggestion!==p&&(t.suggestion=p,u=t.api.N(),z=g.pn(t.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",U4(t,p,z),g.$x(u)&&(u=p.si(),u=g.gd(u,g.rC({},"emb_rel_end")),t.ka("url",u)),(p=(p=p.Ob)&&p.itct)&&g.BK(t.api,t.element,p));c++}g.J(this.element,"ytp-endscreen-paginate",c<l);for(b=this.stills.length-1;b>=c;b--)e=this.stills[b],g.be(e.element),g.oe(e);this.stills.length=c}};
g.h.HH=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.A=0,this.suggestions=Ita(this,a),this.videoData=a,this.Dg())};
g.h.FH=function(){this.A+=this.stills.length;this.Dg()};
g.h.GH=function(){this.A-=this.stills.length;this.Dg()};
g.h.hy=function(){return!!this.u.w};
g.h.Xs=function(a){1===a?(this.C=!1,this.B=this.videoData.clientPlaybackNonce,X4(this.u),this.Fa()&&this.Dg()):(this.C=!0,this.Fa()&&b5(this)&&(2===a?W4(this.u):3===a&&Y4(this.u)))};
g.h.EH=function(a){if(a){for(a=0;a<this.stills.length;a++)g.DK(this.U,this.stills[a].element,!0);this.Xs(1)}else this.B=null,this.C=!1;this.Dg()};
g.h.Ws=function(){return this.Fa()&&b5(this)};g.r(d5,g.KK);g.h=d5.prototype;g.h.Hy=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!Jta(this.player)||b;var c=a.gj||g.iy(a.Qa),d=g.ZR(this.player.app);a=a.mutedAutoplay;return b&&!c&&!d&&!a};
g.h.Gy=function(){return this.endScreen.Ws()};
g.h.mG=function(){return this.Gy()?this.endScreen.hy():!1};
g.h.X=function(){g.MP(this.player.app,"endscreen",void 0);g.KK.prototype.X.call(this)};
g.h.load=function(){g.KK.prototype.load.call(this);this.endScreen.show()};
g.h.unload=function(){g.KK.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.h.DH=function(a){this.Hy()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.h.XK=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.h.TB=function(){g.MP(this.player.app,"endscreen",void 0);var a=this.player.getVideoData();a=new g.HC(Math.max(1E3*(a.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var b=new g.HC(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.tK(this.player,[a,b])};g.ZK.endscreen=d5;})(_yt_player);
